name: arodion
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.18
  get: ^4.6.5
  smooth_page_indicator:  ^1.0.0+2
  flutter_otp_text_field: ^1.1.0+2
  modern_form_line_awesome_icons: ^2.0.1
  flutter_pdfview: ^1.3.1
  google_nav_bar: ^5.0.6
  syncfusion_flutter_pdfviewer: ^22.2.5
  flutter_windowmanager: ^0.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  syncfusion_flutter_pdf: ^22.2.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0





flutter:


  uses-material-design: true
  assets:  
            -    assets/image/arodion.png
            -    assets/image/FP.png
            -    assets/image/pp.jpg
            -    assets/image/Bitmap.png
            -    assets/image/book-1.png
            -    assets/image/book-2.png
            -    assets/image/book-3.png
            -    assets/image/bg.png
            -    assets/pdf/Distributed.pdf
            -    assets/pdf/tag.pdf
            -    assets/image/promo.png
            -    assets/image/chapa.jpg
            -    assets/image/telebirr.png
  
  